### ISSUE TITLE
Enhancement - use project inside floydhub/dl-docker

### ISSUE THREAD

**Issue by johndpope** [hpssjellis/google-magenta-midi-music-on-linux-hello-world#3]
It might be easier for people to use a contained environment like  dl-docker for quickly getting up and running. (would also reduce headaches trouble shooting different environments.)
https://github.com/floydhub/dl-docker

**Comment by johndpope** [comment]
might be an idea to use a gist too as the setup bash script seems to have testing stuff.
(using a gist - people can contribute / update without forking / submitting pull requests.)
https://gist.github.com/johndpope/97c41356639e7add93dd3c05c8f7da8f

**Comment by hpssjellis** [comment]
Good idea. I am familiar with docker as one of my githubs installs an online android sdk enviornment at 

https://github.com/hpssjellis/templates/blob/master/ws-android/Dockerfile

but I normally work with cloud9 and getting them to install my docker file on their system is confusing. Any idea if docker can be run as an online service, instead of on your linux or windows machine?

**Comment by johndpope** [comment]
I haven't used this but given the above libraries reference this I'm sure they would be happy to help with any trouble  - https://www.floydhub.com/
I did run into trouble using digitalocean.com
https://www.digitalocean.com/community/tags/docker?type=tutorials


It's good that nvidia are providing support for docker machine learning 
https://github.com/NVIDIA/nvidia-docker

**Comment by johndpope** [comment]
spring cleaning my github issues. Thanks @hpssjellis for your efforts here.
